version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run : cd states_rebuilder_package
      - run: flutter test --coverage
      - run: bash <(curl -s https://codecov.io/bash)
